### ISSUE TITLE
[middle][Kodi Plugin] Code Refactor

### ISSUE THREAD

**Issue by jugendhacker** [jugendhacker/plugin.audio.mstream#1]
The code needs to be refatored and for example the play part can be moved to an extra file! For any questions just ask me I will help as I can.

**Comment by illright** [comment]
I'll give it a go

**Comment by jugendhacker** [comment]
@illright cool I will wait for your PR, if there are questions feel free to aks

**Comment by illright** [comment]
Okay, here are some questions:
- What is a [`path`](https://github.com/jugendhacker/plugin.audio.mstream/blob/master/addon.py#L44)?
- What is a [`URL`](https://github.com/jugendhacker/plugin.audio.mstream/blob/master/addon.py#L11)?
- Is "DefaultFolger" a typo [here](https://github.com/jugendhacker/plugin.audio.mstream/blob/master/addon.py#L40)?

**Comment by illright** [comment]
More questions, @jugendhacker:
- What is the script doing when no mode is passed?
- What is the script doing when mode is set to files?

**Comment by jugendhacker** [comment]
> * What is a path?

It is the path wich the user currently browsing on the server

> * What is a URL?

That's the launching path of the plugin in Kodi, you need it for navigation on menu items, I think if you exlude a function to another file you have to append this to the path. So when clicking a menu item it will call the script with the specific path

> * Is "DefaultFolger" a typo here?

Yes Typo, you could correct it, if you want

> * What is the script doing when no mode is passed?

It should build a menu where you can browse the filesystem on the server or in future also the albums and artists, as seen [in Line 37](https://github.com/jugendhacker/plugin.audio.mstream/blob/master/addon.py#L37) an following

> * What is the script doing when mode is set to files?

It builds up the file system list, and first if there are more than one vpaths on the server it will let you select one vpath
